using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace Vita.Entities {

  /// <summary>Provides helper method to run asynchronous methods  synchronously.</summary>
  /// <remarks>There is a big problem out there with introduction of async methods. If you have async
  /// method, you are practically forced to call it with await from another async method. However, 
  /// with a lot of existing code not changed overnight, you often need to call the new-style async 
  /// method from old-style sync method. And it is not so simple, it turns out. Task.Run seems to work 
  /// in unit tests (console apps) but results in thread deadlock under ASP.NET. 
  /// Try to find a solution on the web - you will be surprised. Seems like this safe sync/async bridge is a grave secret that MS keeps from anyone.
  /// WTF?!!! 
  /// After several tries and fails, I found this version that works (RunSync) - found in code generated by MS tool. 
  /// </remarks>
  public static class AsyncHelper {

    public static T RunSync<T>(Func<Task<T>> func, bool unwrapException = true) {
      try {
        var result = Task.Factory.StartNew(func).Unwrap().GetAwaiter().GetResult();
        return result;
      } catch(AggregateException exc) {
        if(unwrapException)
          throw exc.InnerExceptions[0];
        else 
          throw; 
      }
    }

    public static void RunSync(Func<Task> action, bool unwrapException = true) {
      try {
        Task.Factory.StartNew(action).Unwrap().GetAwaiter().GetResult();
      } catch(AggregateException exc) {
        if(unwrapException)
          throw exc.InnerExceptions[0];
        else
          throw;
      }
    }

  }//class
}
