using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Vita.Modules.Login {


  [Flags]
  public enum LoginFlags {
    None = 0x00,
    Disabled = 1, // might be disabled when user is no longer there
    Suspended = 1 << 1,
    PasswordExpired = 1 << 2,

    RequireMultiFactor = 1 << 4,
    DoNotConcealMembership = 1 << 5,

    AutoGenerated = 1 << 8,
    OneTimePassword = 1 << 9,
    OneTimePasswordUsed = 1 << 10, //set after password was used for login

    Inactive = Disabled | Suspended | PasswordExpired,
  }

  [Flags]
  public enum SecretQuestionFlags {
    None = 0,
    Disabled = 1,
    Private = 1 << 1, // When created through "Write my own question"
    Extra = 1 << 2, // not showing by default
  }

  public enum DeviceTrustLevel {
    None,
    AllowSingleFactor, // one-factor identification is enough
    KeepLoggedIn, // Do not expire session
  }

  public enum LoginProcessType {
    PasswordReset,  // resetting password
    FactorVerification, // email or phone verification
    MultiFactorLogin, // multi-factor login process
  }

  [Flags]
  public enum ExtraFactorTypes {
    None = 0,
    Email = 1,
    Phone = 1 << 1,
    SecretQuestions = 1 << 2,
    GoogleAuthenticator = 1 << 3, 
  }


  public enum LoginAttemptStatus {
    Failed,
    AccountInactive,
    PendingMultifactor,
    Success,
  }

  [Flags]
  public enum PostLoginActions {
    None = 0,
    WarnPasswordExpires = 1,
    ForceChangePassword = 1 << 1,
    SetupExtraFactors = 1 << 3, 
  }

  /// <summary>Event types for LoginLog, LoginEvent and IncidentLog. </summary>
  public enum LoginEventType {
    // Login/logout events
    Login,
    Logout,
    LoginPendingMultiFactor,
    LoginFailed,
    LoginSuspended,
    LoginDisabled,
    PasswordExpired,
    LoginReactivated,

    //management
    LoginCreated,
    LoginChanged,
    PasswordChanged,
    OneTimePasswordSet,
    SecretQuestionChanged,
    TrustedDeviceChanged,

    //Processes
    MultiFactorLoginStarted,
    MultiFactorLoginCompleted,
    PasswordResetStarted,
    FactorVerificationStarted,
    PinSent,
    PinMismatch,
    PinMatched,
    QuestionAnswersFailed,
    QuestionAnswersSucceeded,
    ProcessAborted,
  }

  public enum LoginProcessStatus {
    Active,
    Completed,
    Expired,
    AbortedAsFraud,
  }

  [Flags]
  public enum LoginProcessFlags {
    None = 0,
    Obscured = 1, // user did not confirm any factors, so do not disclose to UI if user exist or not in the database
  }

  public enum DeviceType {
    Unknown = 0,
    Computer = 1,
    Tablet = 2, 
    Phone = 3,
    Custom = 5,
  }

}
